import { readFile, mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { setupSpec, type SetupSpec } from "./spec.js";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const checkOnly = process.argv.includes("--check");

function assertSpec(spec: SetupSpec): void {
  const modelIds = new Set<string>();
  for (const preset of spec.modelPresets) {
    if (modelIds.has(preset.model)) throw new Error(`Duplicate model preset: ${preset.model}`);
    if (!preset.reasoningEffort || preset.contextWindow <= 0)
      throw new Error(`Incomplete model preset: ${preset.model}`);
    modelIds.add(preset.model);
  }
  for (const required of ["Title", "Ordered", "Info", "Detail", "Success", "Warning", "Error", "Prompt", "Change"]) {
    if (!spec.typeStyles[required]) throw new Error(`Missing UI type style: ${required}`);
  }
}

function quotePowerShell(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

function quoteShell(value: string): string {
  return "'" + value.replaceAll("'", "'\"'\"'") + "'";
}

function renderPowerShellPresets(spec: SetupSpec): string {
  const rows = spec.modelPresets.map(
    (preset) =>
      `    [pscustomobject]@{ Model = ${quotePowerShell(preset.model)}; ReasoningEffort = ${quotePowerShell(preset.reasoningEffort)}; ContextWindow = ${preset.contextWindow} }`,
  );
  return ["$MODEL_PRESETS = @(", ...rows, ")"].join("\n");
}

function renderPowerShellMessages(spec: SetupSpec): string {
  const rows = Object.entries(spec.messages).map(([name, value]) => `    ${name} = ${quotePowerShell(value)}`);
  return ["$MESSAGES = @{", ...rows, "}"].join("\n");
}

function renderPowerShellTypes(spec: SetupSpec): string {
  const rows = Object.entries(spec.typeStyles).map(
    ([name, style]) =>
      `    ${name} = [pscustomobject]@{ Marker = ${quotePowerShell(style.marker)}; Color = [ConsoleColor]::${style.powershellColor} }`,
  );
  return ["$TYPE_STYLES = @{", ...rows, "}"].join("\n");
}

function renderShellPresets(spec: SetupSpec): string {
  const cases = spec.modelPresets.flatMap((preset, index) => [
    "    " + (index + 1) + ")",
    "      PRESET_MODEL=" + quoteShell(preset.model),
    "      PRESET_REASONING_EFFORT=" + quoteShell(preset.reasoningEffort),
    "      PRESET_CONTEXT_WINDOW=" + quoteShell(String(preset.contextWindow)),
    "      ;;",
  ]);
  return [
    "MODEL_PRESET_COUNT=" + spec.modelPresets.length,
    "load_model_preset() {",
    "  case $1 in",
    ...cases,
    "    *) return 1 ;;",
    "  esac",
    "}",
  ].join("\n");
}

function toShellPrintfFormat(value: string): string {
  return value
    .replaceAll("\\", "\\\\")
    .replaceAll("%", "%%")
    .replaceAll("\n", "\\n")
    .replace(/\{\d+\}/g, "%s");
}

function renderShellMessages(spec: SetupSpec): string {
  const cases = Object.entries(spec.messages).map(([name, value]) => {
    const indexes = [...value.matchAll(/\{(\d+)\}/g)].map((match) => Number(match[1]) + 1);
    const argumentsList = indexes.map((index) => `"\${${index}-}"`).join(" ");
    const command =
      indexes.length > 0
        ? "printf " + quoteShell(toShellPrintfFormat(value)) + " " + argumentsList
        : "printf '%s' " + quoteShell(value);
    return "    " + name + ") " + command + " ;;";
  });
  return ["message() {", "  key=$1", "  shift", "  case $key in", ...cases, "    *) return 1 ;;", "  esac", "}"].join(
    "\n",
  );
}

function renderShellTypes(spec: SetupSpec): string {
  const cases = Object.entries(spec.typeStyles).map(
    ([name, style]) =>
      "    " +
      name +
      ") TYPE_MARKER=" +
      quoteShell(style.marker) +
      "; TYPE_COLOR=" +
      quoteShell(String(style.ansiColor)) +
      " ;;",
  );
  const orderedColor = spec.typeStyles.Ordered?.ansiColor;
  if (orderedColor === undefined) throw new Error("Missing Ordered UI type style");
  return [
    "load_type_style() {",
    "  case $1 in",
    ...cases,
    "    ''|*[!0-9]*) return 1 ;;",
    "    *) TYPE_MARKER=$1; TYPE_COLOR=" + quoteShell(String(orderedColor)) + " ;;",
    "  esac",
    "}",
  ].join("\n");
}

function replacePlaceholder(template: string, name: string, value: string): string {
  const marker = `# {{${name}}}`;
  const occurrences = template.split(marker).length - 1;
  if (occurrences !== 1) throw new Error(`Expected one ${marker} placeholder, found ${occurrences}`);
  return template.replace(marker, value);
}

async function renderPowerShell(spec: SetupSpec): Promise<string> {
  const templatePath = resolve(projectRoot, "templates/codex-provider-setup.ps1.tmpl");
  let output = await readFile(templatePath, "utf8");
  output = replacePlaceholder(output, "GENERATED_HEADER", "# Code generated by `pnpm generate`. DO NOT EDIT.");
  output = replacePlaceholder(output, "SCRIPT_VERSION", `$SCRIPT_VERSION = ${quotePowerShell(spec.version)}`);
  output = replacePlaceholder(output, "MODEL_PRESETS", renderPowerShellPresets(spec));
  output = replacePlaceholder(output, "MESSAGES", renderPowerShellMessages(spec));
  output = replacePlaceholder(output, "TYPE_STYLES", renderPowerShellTypes(spec));
  return output.replaceAll("\r\n", "\n");
}

async function renderShell(spec: SetupSpec): Promise<string> {
  const templatePath = resolve(projectRoot, "templates/codex-provider-setup.sh.tmpl");
  let output = await readFile(templatePath, "utf8");
  output = replacePlaceholder(output, "GENERATED_HEADER", "# Code generated by pnpm generate. DO NOT EDIT.");
  output = replacePlaceholder(output, "SCRIPT_VERSION", "SCRIPT_VERSION=" + quoteShell(spec.version));
  output = replacePlaceholder(output, "MODEL_PRESETS", renderShellPresets(spec));
  output = replacePlaceholder(output, "MESSAGES", renderShellMessages(spec));
  output = replacePlaceholder(output, "TYPE_STYLES", renderShellTypes(spec));
  return output.replaceAll("\r\n", "\n");
}

async function emit(path: string, content: string): Promise<void> {
  const normalized = content.endsWith("\n") ? content : `${content}\n`;
  if (/\{\{[A-Z0-9_]+\}\}/.test(normalized)) throw new Error(`Unresolved placeholder in generated file: ${path}`);
  if (/[^\x00-\x7F]/.test(normalized)) throw new Error(`Generated file is not ASCII: ${path}`);
  if (checkOnly) {
    const current = await readFile(path, "utf8").catch(() => "");
    if (current.replaceAll("\r\n", "\n") !== normalized) throw new Error(`Generated file is stale: ${path}`);
    return;
  }
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, normalized, "utf8");
}

assertSpec(setupSpec);
const packageJson = JSON.parse(await readFile(resolve(projectRoot, "package.json"), "utf8")) as { version?: string };
if (packageJson.version !== setupSpec.version) {
  throw new Error(`Version mismatch: package.json=${packageJson.version ?? "missing"}, spec=${setupSpec.version}`);
}
await emit(resolve(projectRoot, "dist/codex-provider-setup.ps1"), await renderPowerShell(setupSpec));
await emit(resolve(projectRoot, "dist/codex-provider-setup.sh"), await renderShell(setupSpec));
